/// Flutter icons IconLogin
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconLogin
///      fonts:
///       - asset: fonts/IconLogin.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IconLogin {
  IconLogin._();

  static const _kFontFam = 'IconLogin';
  static const String? _kFontPkg = null;

  static const IconData icons8_logo_de_google = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_facebook__1_ = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_linkedin = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
